-- Broad ticker catalog across sectors, both markets
-- Generated as a deduplicated set; safe to re-run (ON CONFLICT DO NOTHING)

INSERT INTO tickers (ticker, company_name, sector, exchange) VALUES
  ('TCS', 'Tata Consultancy Services', 'IT', 'NSE'),
  ('INFY', 'Infosys', 'IT', 'NSE'),
  ('WIPRO', 'Wipro', 'IT', 'NSE'),
  ('HCLTECH', 'HCL Technologies', 'IT', 'NSE'),
  ('TECHM', 'Tech Mahindra', 'IT', 'NSE'),
  ('LTIM', 'LTIMindtree', 'IT', 'NSE'),
  ('MPHASIS', 'Mphasis', 'IT', 'NSE'),
  ('PERSISTENT', 'Persistent Systems', 'IT', 'NSE'),
  ('COFORGE', 'Coforge', 'IT', 'NSE'),
  ('HDFCBANK', 'HDFC Bank', 'Banking', 'NSE'),
  ('ICICIBANK', 'ICICI Bank', 'Banking', 'NSE'),
  ('SBIN', 'State Bank of India', 'Banking', 'NSE'),
  ('KOTAKBANK', 'Kotak Mahindra Bank', 'Banking', 'NSE'),
  ('AXISBANK', 'Axis Bank', 'Banking', 'NSE'),
  ('INDUSINDBK', 'IndusInd Bank', 'Banking', 'NSE'),
  ('BANKBARODA', 'Bank of Baroda', 'Banking', 'NSE'),
  ('PNB', 'Punjab National Bank', 'Banking', 'NSE'),
  ('IDFCFIRSTB', 'IDFC First Bank', 'Banking', 'NSE'),
  ('FEDERALBNK', 'Federal Bank', 'Banking', 'NSE'),
  ('AUBANK', 'AU Small Finance Bank', 'Banking', 'NSE'),
  ('BAJFINANCE', 'Bajaj Finance', 'Financial Services', 'NSE'),
  ('BAJAJFINSV', 'Bajaj Finserv', 'Financial Services', 'NSE'),
  ('HDFCLIFE', 'HDFC Life Insurance', 'Financial Services', 'NSE'),
  ('SBILIFE', 'SBI Life Insurance', 'Financial Services', 'NSE'),
  ('ICICIPRULI', 'ICICI Prudential Life Insurance', 'Financial Services', 'NSE'),
  ('ICICIGI', 'ICICI Lombard General Insurance', 'Financial Services', 'NSE'),
  ('SBICARD', 'SBI Cards and Payment Services', 'Financial Services', 'NSE'),
  ('MUTHOOTFIN', 'Muthoot Finance', 'Financial Services', 'NSE'),
  ('CHOLAFIN', 'Cholamandalam Investment and Finance', 'Financial Services', 'NSE'),
  ('PFC', 'Power Finance Corporation', 'Financial Services', 'NSE'),
  ('RECLTD', 'REC Limited', 'Financial Services', 'NSE'),
  ('RELIANCE', 'Reliance Industries', 'Energy', 'NSE'),
  ('ONGC', 'Oil and Natural Gas Corporation', 'Energy', 'NSE'),
  ('NTPC', 'NTPC Limited', 'Energy', 'NSE'),
  ('POWERGRID', 'Power Grid Corporation of India', 'Energy', 'NSE'),
  ('COALINDIA', 'Coal India', 'Energy', 'NSE'),
  ('BPCL', 'Bharat Petroleum Corporation', 'Energy', 'NSE'),
  ('IOC', 'Indian Oil Corporation', 'Energy', 'NSE'),
  ('GAIL', 'GAIL India', 'Energy', 'NSE'),
  ('PETRONET', 'Petronet LNG', 'Energy', 'NSE'),
  ('TATAPOWER', 'Tata Power Company', 'Energy', 'NSE'),
  ('ADANIGREEN', 'Adani Green Energy', 'Energy', 'NSE'),
  ('ADANIPOWER', 'Adani Power', 'Energy', 'NSE'),
  ('JSWENERGY', 'JSW Energy', 'Energy', 'NSE'),
  ('TATAMOTORS', 'Tata Motors', 'Auto', 'NSE'),
  ('MARUTI', 'Maruti Suzuki India', 'Auto', 'NSE'),
  ('M&M', 'Mahindra & Mahindra', 'Auto', 'NSE'),
  ('BAJAJ-AUTO', 'Bajaj Auto', 'Auto', 'NSE'),
  ('EICHERMOT', 'Eicher Motors', 'Auto', 'NSE'),
  ('HEROMOTOCO', 'Hero MotoCorp', 'Auto', 'NSE'),
  ('TVSMOTOR', 'TVS Motor Company', 'Auto', 'NSE'),
  ('ASHOKLEY', 'Ashok Leyland', 'Auto', 'NSE'),
  ('BOSCHLTD', 'Bosch Limited', 'Auto', 'NSE'),
  ('MOTHERSON', 'Samvardhana Motherson International', 'Auto', 'NSE'),
  ('BALKRISIND', 'Balkrishna Industries', 'Auto', 'NSE'),
  ('MRF', 'MRF Limited', 'Auto', 'NSE'),
  ('APOLLOTYRE', 'Apollo Tyres', 'Auto', 'NSE'),
  ('HINDUNILVR', 'Hindustan Unilever', 'FMCG', 'NSE'),
  ('ITC', 'ITC Limited', 'FMCG', 'NSE'),
  ('NESTLEIND', 'Nestle India', 'FMCG', 'NSE'),
  ('BRITANNIA', 'Britannia Industries', 'FMCG', 'NSE'),
  ('DABUR', 'Dabur India', 'FMCG', 'NSE'),
  ('GODREJCP', 'Godrej Consumer Products', 'FMCG', 'NSE'),
  ('MARICO', 'Marico', 'FMCG', 'NSE'),
  ('TATACONSUM', 'Tata Consumer Products', 'FMCG', 'NSE'),
  ('COLPAL', 'Colgate-Palmolive India', 'FMCG', 'NSE'),
  ('VBL', 'Varun Beverages', 'FMCG', 'NSE'),
  ('SUNPHARMA', 'Sun Pharmaceutical Industries', 'Pharma', 'NSE'),
  ('DRREDDY', 'Dr. Reddy''s Laboratories', 'Pharma', 'NSE'),
  ('CIPLA', 'Cipla', 'Pharma', 'NSE'),
  ('DIVISLAB', 'Divi''s Laboratories', 'Pharma', 'NSE'),
  ('LUPIN', 'Lupin Limited', 'Pharma', 'NSE'),
  ('AUROPHARMA', 'Aurobindo Pharma', 'Pharma', 'NSE'),
  ('APOLLOHOSP', 'Apollo Hospitals Enterprise', 'Healthcare', 'NSE'),
  ('FORTIS', 'Fortis Healthcare', 'Healthcare', 'NSE'),
  ('MAXHEALTH', 'Max Healthcare Institute', 'Healthcare', 'NSE'),
  ('BHARTIARTL', 'Bharti Airtel', 'Telecom', 'NSE'),
  ('IDEA', 'Vodafone Idea', 'Telecom', 'NSE'),
  ('TATASTEEL', 'Tata Steel', 'Metals', 'NSE'),
  ('JSWSTEEL', 'JSW Steel', 'Metals', 'NSE'),
  ('HINDALCO', 'Hindalco Industries', 'Metals', 'NSE'),
  ('VEDANTA', 'Vedanta Limited', 'Metals', 'NSE'),
  ('SAIL', 'Steel Authority of India', 'Metals', 'NSE'),
  ('JINDALSTEL', 'Jindal Steel & Power', 'Metals', 'NSE'),
  ('NMDC', 'NMDC Limited', 'Metals', 'NSE'),
  ('HINDZINC', 'Hindustan Zinc', 'Metals', 'NSE'),
  ('ULTRACEMCO', 'UltraTech Cement', 'Cement', 'NSE'),
  ('SHREECEM', 'Shree Cement', 'Cement', 'NSE'),
  ('AMBUJACEM', 'Ambuja Cements', 'Cement', 'NSE'),
  ('ACC', 'ACC Limited', 'Cement', 'NSE'),
  ('LT', 'Larsen & Toubro', 'Infrastructure', 'NSE'),
  ('ADANIPORTS', 'Adani Ports and SEZ', 'Infrastructure', 'NSE'),
  ('GMRINFRA', 'GMR Airports Infrastructure', 'Infrastructure', 'NSE'),
  ('SIEMENS', 'Siemens India', 'Industrials', 'NSE'),
  ('ABB', 'ABB India', 'Industrials', 'NSE'),
  ('BEL', 'Bharat Electronics', 'Industrials', 'NSE'),
  ('HAL', 'Hindustan Aeronautics', 'Industrials', 'NSE'),
  ('CONCOR', 'Container Corporation of India', 'Industrials', 'NSE'),
  ('TITAN', 'Titan Company', 'Consumer Durables', 'NSE'),
  ('HAVELLS', 'Havells India', 'Consumer Durables', 'NSE'),
  ('VOLTAS', 'Voltas', 'Consumer Durables', 'NSE'),
  ('CROMPTON', 'Crompton Greaves Consumer Electricals', 'Consumer Durables', 'NSE'),
  ('ASIANPAINT', 'Asian Paints', 'Paints', 'NSE'),
  ('BERGEPAINT', 'Berger Paints India', 'Paints', 'NSE'),
  ('DLF', 'DLF Limited', 'Realty', 'NSE'),
  ('GODREJPROP', 'Godrej Properties', 'Realty', 'NSE'),
  ('OBEROIRLTY', 'Oberoi Realty', 'Realty', 'NSE'),
  ('SUNTV', 'Sun TV Network', 'Media', 'NSE'),
  ('ZEEL', 'Zee Entertainment Enterprises', 'Media', 'NSE'),
  ('PIDILITIND', 'Pidilite Industries', 'Chemicals', 'NSE'),
  ('SRF', 'SRF Limited', 'Chemicals', 'NSE'),
  ('UPL', 'UPL Limited', 'Chemicals', 'NSE'),
  ('DMART', 'Avenue Supermarts', 'Retail', 'NSE'),
  ('TRENT', 'Trent Limited', 'Retail', 'NSE'),
  ('INDIGO', 'InterGlobe Aviation', 'Aviation', 'NSE'),
  ('ADANIENT', 'Adani Enterprises', 'Diversified', 'NSE'),
  ('GRASIM', 'Grasim Industries', 'Diversified', 'NSE'),
  ('PAGEIND', 'Page Industries', 'Textiles', 'NSE'),
  ('AAPL', 'Apple Inc.', 'Technology', 'NASDAQ'),
  ('MSFT', 'Microsoft Corporation', 'Technology', 'NASDAQ'),
  ('GOOGL', 'Alphabet Inc.', 'Technology', 'NASDAQ'),
  ('NVDA', 'NVIDIA Corporation', 'Technology', 'NASDAQ'),
  ('AVGO', 'Broadcom Inc.', 'Technology', 'NASDAQ'),
  ('ADBE', 'Adobe Inc.', 'Technology', 'NASDAQ'),
  ('CRM', 'Salesforce Inc.', 'Technology', 'NASDAQ'),
  ('ORCL', 'Oracle Corporation', 'Technology', 'NASDAQ'),
  ('CSCO', 'Cisco Systems', 'Technology', 'NASDAQ'),
  ('INTC', 'Intel Corporation', 'Technology', 'NASDAQ'),
  ('AMD', 'Advanced Micro Devices', 'Technology', 'NASDAQ'),
  ('QCOM', 'Qualcomm Incorporated', 'Technology', 'NASDAQ'),
  ('TXN', 'Texas Instruments', 'Technology', 'NASDAQ'),
  ('IBM', 'International Business Machines', 'Technology', 'NASDAQ'),
  ('NOW', 'ServiceNow Inc.', 'Technology', 'NASDAQ'),
  ('INTU', 'Intuit Inc.', 'Technology', 'NASDAQ'),
  ('PANW', 'Palo Alto Networks', 'Technology', 'NASDAQ'),
  ('MU', 'Micron Technology', 'Technology', 'NASDAQ'),
  ('SNOW', 'Snowflake Inc.', 'Technology', 'NASDAQ'),
  ('PLTR', 'Palantir Technologies', 'Technology', 'NASDAQ'),
  ('TSLA', 'Tesla Inc.', 'Automotive', 'NASDAQ'),
  ('F', 'Ford Motor Company', 'Automotive', 'NASDAQ'),
  ('GM', 'General Motors Company', 'Automotive', 'NASDAQ'),
  ('RIVN', 'Rivian Automotive', 'Automotive', 'NASDAQ'),
  ('AMZN', 'Amazon.com Inc.', 'Retail', 'NASDAQ'),
  ('WMT', 'Walmart Inc.', 'Retail', 'NASDAQ'),
  ('COST', 'Costco Wholesale Corporation', 'Retail', 'NASDAQ'),
  ('TGT', 'Target Corporation', 'Retail', 'NASDAQ'),
  ('HD', 'Home Depot Inc.', 'Retail', 'NASDAQ'),
  ('LOW', 'Lowe''s Companies', 'Retail', 'NASDAQ'),
  ('EBAY', 'eBay Inc.', 'Retail', 'NASDAQ'),
  ('ETSY', 'Etsy Inc.', 'Retail', 'NASDAQ'),
  ('META', 'Meta Platforms Inc.', 'Media', 'NASDAQ'),
  ('NFLX', 'Netflix Inc.', 'Media', 'NASDAQ'),
  ('DIS', 'The Walt Disney Company', 'Media', 'NASDAQ'),
  ('CMCSA', 'Comcast Corporation', 'Media', 'NASDAQ'),
  ('WBD', 'Warner Bros. Discovery', 'Media', 'NASDAQ'),
  ('GILD', 'Gilead Sciences', 'Healthcare', 'NASDAQ'),
  ('AMGN', 'Amgen Inc.', 'Healthcare', 'NASDAQ'),
  ('REGN', 'Regeneron Pharmaceuticals', 'Healthcare', 'NASDAQ'),
  ('VRTX', 'Vertex Pharmaceuticals', 'Healthcare', 'NASDAQ'),
  ('MRNA', 'Moderna Inc.', 'Healthcare', 'NASDAQ'),
  ('ISRG', 'Intuitive Surgical', 'Healthcare', 'NASDAQ'),
  ('BIIB', 'Biogen Inc.', 'Healthcare', 'NASDAQ'),
  ('PYPL', 'PayPal Holdings', 'Finance', 'NASDAQ'),
  ('SQ', 'Block Inc.', 'Finance', 'NASDAQ'),
  ('COIN', 'Coinbase Global', 'Finance', 'NASDAQ'),
  ('SOFI', 'SoFi Technologies', 'Finance', 'NASDAQ'),
  ('AXP', 'American Express Company', 'Finance', 'NASDAQ'),
  ('PEP', 'PepsiCo Inc.', 'Consumer Goods', 'NASDAQ'),
  ('KO', 'The Coca-Cola Company', 'Consumer Goods', 'NASDAQ'),
  ('MCD', 'McDonald''s Corporation', 'Consumer Goods', 'NASDAQ'),
  ('SBUX', 'Starbucks Corporation', 'Consumer Goods', 'NASDAQ'),
  ('NKE', 'Nike Inc.', 'Consumer Goods', 'NASDAQ'),
  ('PG', 'Procter & Gamble Company', 'Consumer Goods', 'NASDAQ'),
  ('MDLZ', 'Mondelez International', 'Consumer Goods', 'NASDAQ'),
  ('KHC', 'Kraft Heinz Company', 'Consumer Goods', 'NASDAQ'),
  ('BA', 'Boeing Company', 'Industrials', 'NASDAQ'),
  ('CAT', 'Caterpillar Inc.', 'Industrials', 'NASDAQ'),
  ('HON', 'Honeywell International', 'Industrials', 'NASDAQ'),
  ('GE', 'General Electric Company', 'Industrials', 'NASDAQ'),
  ('UPS', 'United Parcel Service', 'Industrials', 'NASDAQ'),
  ('LMT', 'Lockheed Martin Corporation', 'Industrials', 'NASDAQ'),
  ('XOM', 'Exxon Mobil Corporation', 'Energy', 'NASDAQ'),
  ('CVX', 'Chevron Corporation', 'Energy', 'NASDAQ'),
  ('OXY', 'Occidental Petroleum', 'Energy', 'NASDAQ'),
  ('SLB', 'Schlumberger Limited', 'Energy', 'NASDAQ'),
  ('VZ', 'Verizon Communications', 'Telecom', 'NASDAQ'),
  ('T', 'AT&T Inc.', 'Telecom', 'NASDAQ'),
  ('TMUS', 'T-Mobile US Inc.', 'Telecom', 'NASDAQ'),
  ('BKNG', 'Booking Holdings', 'Travel', 'NASDAQ'),
  ('ADI', 'Analog Devices', 'Technology', 'NASDAQ'),
  ('LRCX', 'Lam Research Corporation', 'Technology', 'NASDAQ'),
  ('KLAC', 'KLA Corporation', 'Technology', 'NASDAQ'),
  ('MRVL', 'Marvell Technology', 'Technology', 'NASDAQ'),
  ('ADSK', 'Autodesk Inc.', 'Technology', 'NASDAQ'),
  ('WDAY', 'Workday Inc.', 'Technology', 'NASDAQ'),
  ('TEAM', 'Atlassian Corporation', 'Technology', 'NASDAQ'),
  ('ZM', 'Zoom Communications', 'Technology', 'NASDAQ'),
  ('DOCU', 'DocuSign Inc.', 'Technology', 'NASDAQ'),
  ('MELI', 'MercadoLibre Inc.', 'Retail', 'NASDAQ'),
  ('ABNB', 'Airbnb Inc.', 'Travel', 'NASDAQ'),
  ('MAR', 'Marriott International', 'Travel', 'NASDAQ'),
  ('EA', 'Electronic Arts', 'Media', 'NASDAQ'),
  ('TTD', 'The Trade Desk', 'Media', 'NASDAQ'),
  ('ROKU', 'Roku Inc.', 'Media', 'NASDAQ'),
  ('PDD', 'PDD Holdings', 'Retail', 'NASDAQ'),
  ('JD', 'JD.com Inc.', 'Retail', 'NASDAQ'),
  ('BIDU', 'Baidu Inc.', 'Technology', 'NASDAQ'),
  ('NTES', 'NetEase Inc.', 'Media', 'NASDAQ'),
  ('CSX', 'CSX Corporation', 'Industrials', 'NASDAQ'),
  ('PCAR', 'PACCAR Inc.', 'Industrials', 'NASDAQ'),
  ('PAYX', 'Paychex Inc.', 'Finance', 'NASDAQ'),
  ('FI', 'Fiserv Inc.', 'Finance', 'NASDAQ'),
  ('MDB', 'MongoDB Inc.', 'Technology', 'NASDAQ')

ON CONFLICT (ticker) DO NOTHING;
